
-- Permissao Gerente
INSERT INTO permissao (nome, descricao) VALUES ('EDITAR_USUARIOS', 'Permite criar ou editar usuário existente.'), ('EDITAR_PERMISSAO', 'Permite criar ou editar permissão existente.'), ('EDITAR_GRUPO', 'Permite criar ou editar grupo existente.'), ('CONSULTAR_USUARIOS', 'Permite consultar usuário existente.');

-- Permissao Gerente/Cadastrador
INSERT INTO permissao (nome, descricao) VALUES ('EDITAR_FORMA_PAGAMENTO', 'Permite criar ou editar forma de pagamento.'), ('EDITAR_PRODUTO', 'Permite criar ou editar produto cadastrado.');

-- Permissao Gerente/Vendedor
INSERT INTO permissao (nome, descricao) VALUES ('EDITAR_PEDIDO', 'Permite editar informações do pedido.'), ('GERAR_RELATORIOS', 'Permite gerar relatórios.');

-- Permissao Gerente/Cadastrador/Vendedor/Cliente
INSERT INTO permissao (nome, descricao) VALUES ('CONSULTAR PRODUTO', 'Permite visualizar informações do produto.'), ('EDITAR_DADOS', 'Permite criar ou editar dados individuais.'), ('CRIAR_PEDIDO', 'Permite criar novo pedido');

-- Grupo
INSERT INTO grupo (nome) VALUES ('Gerente'), ('Vendedor'), ('Cadastrador'), ('Cliente');

-- Pagamento
INSERT INTO pagamento (descricao, ativo, data_atualizacao) VALUES ('Cartão de crédito', true, now()), ('Cartão de débito', true, now()), ('Dinheiro', true, now()), ('PIX', true, now());

-- Gênero
INSERT INTO genero (descricao) VALUES ('Masculino'), ('Feminino'), ('Menino'), ('Menina'), ('Unissex');

-- Categoria
INSERT INTO categoria (descricao) VALUES ('Calçados'), ('Roupas'), ('Acessórios');

-- Tipo
-- INSERT INTO tipo (descricao, categoria_id) VALUES	('Botas', 1), ('Chinelos', 1), ('Chuteiras', 1), ('Crocs', 1), ('Sapatênis', 1), ('Tênis', 1), ('Bermudas', 2), ('Calças', 2), ('Camisas', 2), ('Jaquetas', 2), ('Moletons', 2), ('Shorts', 2), ('Vestidos', 2), ('Bonés', 3), ('Malas', 3), ('Meias', 3), ('Mochilas', 3), ('Óculos', 3), ('Relógios', 3);
INSERT INTO tipo (descricao) VALUES	('Botas'), ('Chinelos'), ('Chuteiras'), ('Crocs'), ('Sapatênis'), ('Tênis'), ('Bermudas'), ('Calças'), ('Camisas'), ('Jaquetas'), ('Moletons'), ('Shorts'), ('Vestidos'), ('Bonés'), ('Malas'), ('Meias'), ('Mochilas'), ('Óculos'), ('Relógios');

-- Tamanho
INSERT INTO tamanho	(descricao)	VALUES ('PP'), ('P'), ('M'), ('G'), ('GG'), ('XG'), ('20'), ('22'), ('24'), ('26'), ('28'), ('30'), ('32'), ('34'), ('36'), ('38'), ('40'), ('42'), ('44'), ('46'), ('48'), ('50'), ('Único');

-- Marca
INSERT INTO marca (descricao) VALUES ('Adidas'), ('Amora'), ('Asics'), ('Aramis'), ('Armadilho'), ('Calvin Klein'), ('Colcci'), ('Capricho'), ('Caterpillar'), ('Coca Cola'), ('Everlast'), ('Fila'), ('Kappa'), ('Mizuno'), ('Nike'), ('Oakley'), ('Olympikus'), ('Puma'), ('Lacoste'), ('Reserva'), ('Democrata'), ('Ferracini'), ('Hering');

-- Cor
INSERT INTO cor (descricao, valor) VALUES ('Amarelo', '#F29D36'), ('Azul Claro', '#7DA4CE'), ('Azul Escuro', '#0E4B8B'), ('Bege', '#E5D0BD'), ('Branco', '#FFFFFF'), ('Cinza', '#C3C3C3'), ('Dourado', '#CEA227'), ('Laranja', '#FE6B23'), ('Marrom', '#966D4F'), ('Preto', '#000000'), ('Rosa', '#FF0D97'), ('Roxo', '#752F92'), ('Verde', '#019934'), ('Verde Escuro', '#14381E'), ('Verde Claro', '#77AE6D'), ('Vermelho', '#A40313');

-- Produto

-- Masculino -> Calçados -> Botas
INSERT INTO produto	(nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bota Chelsea Colcci Israel Preta', 'Bota Coturno Masculino Colcci Israel Preta', 'Bota Chelsea Colcci Israel Preta<br>Bota Coturno Masculino Colcci Israel Preta<br>Bico: Redondo<br>Medidas da peça: 12x20cm (Altura X Circunferência)<br>Características: Possui puxador posterior para facilitar o calce<br><br>VERSÁTIL E MODERNA: Coringas para os dias mais frios ou chuvosos, as botas masculinas podem compor looks cheios de estilo que vão do urbano garage ao elegante, podendo ser usadas até mesmo para um visual mais formal para o trabalho!<br><br>RESISTENTE E ATEMPORAL: O Couro é o material obtido através da pele de animal curtida, e pode ter diversos acabamentos. Apresenta resistência e durabilidade, o que torna um material nobre muito utilizado na confecção de calçados, roupas e acessórios. A escolha perfeita para quem deseja um produto duradouro!<br><br>Sobre a marca: Há 30 anos a Colcci é considerada uma das marcas mais influentes da moda brasileira, graças aos seus produtos que aliam qualidade, sofisticação e informação de moda. A marca é um Must-Have de qualquer guarda-roupa, e conta com peças para todas as ocasiões.<br>Produto enviado com nota fiscal!', '18.00', '9.50', '28.00', '500.00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 1, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bota-chelsea-colcci-israel-preta-1-1', 'webp', 10, 1), ('bota-chelsea-colcci-israel-preta-1-2', 'webp', 10, 1), ('bota-chelsea-colcci-israel-preta-1-3', 'webp', 10, 1), ('bota-chelsea-colcci-israel-preta-1-4', 'webp', 10, 1), ('bota-chelsea-colcci-israel-preta-1-5', 'webp', 10, 1), ('bota-chelsea-colcci-israel-preta-1-6', 'webp', 10, 1);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (19, 280.90, 1, 10, 17), (20, 280.90, 1, 10, 18), (23, 280.90, 1, 10, 19);

INSERT INTO produto	(nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bota Coturno Colcci José Café', 'Bota Coturno Masculino Colcci José Café', 'Bota Coturno Colcci José Café<br>Bota Coturno Masculino Colcci José Café<br>Bico: Redondo<br>Medidas da peça: 12x30cm (Altura X Circunferência)<br>Características: Possui solado tratorado<br><br>VERSÁTIL E MODERNA: Coringas para os dias mais frios ou chuvosos, as botas masculinas podem compor looks cheios de estilo que vão do urbano garage ao elegante, podendo ser usadas até mesmo para um visual mais formal para o trabalho!<br><br>RESISTENTE E ATEMPORAL: O Couro é o material obtido através da pele de animal curtida, e pode ter diversos acabamentos. Apresenta resistência e durabilidade, o que torna um material nobre muito utilizado na confecção de calçados, roupas e acessórios. A escolha perfeita para quem deseja um produto duradouro!<br><br>Sobre a marca: Há 30 anos a Colcci é considerada uma das marcas mais influentes da moda brasileira, graças aos seus produtos que aliam qualidade, sofisticação e informação de moda. A marca é um Must-Have de qualquer guarda-roupa, e conta com peças para todas as ocasiões.<br>Produto enviado com nota fiscal!', '18.00', '9.50', '28.00', '500.00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 1, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bota-coturno-colcci-jose-cafe-2-1', 'webp', 10, 2), ('bota-coturno-colcci-jose-cafe-2-2', 'webp', 10, 2), ('bota-coturno-colcci-jose-cafe-2-3', 'webp', 10, 2), ('bota-coturno-colcci-jose-cafe-2-4', 'webp', 10, 2), ('bota-coturno-colcci-jose-cafe-2-5', 'webp', 10, 2), ('bota-coturno-colcci-jose-cafe-2-6', 'webp', 10, 2);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (19, 270.90, 2, 10, 17), (20, 270.90, 2, 10, 18), (19, 270.90, 2, 10, 19), (19, 270.90, 2, 10, 20);

INSERT INTO produto	(nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bota Chelsea Colcci Israel Café', 'Bota Coturno Masculino Colcci Israel Café', 'Bota Chelsea Colcci Israel Café<br>Bota Coturno Masculino Colcci Israel Café<br>Bico: Redondo<br>Medidas da peça: 12x20cm (Altura X Circunferência)<br>Características: Possui puxador posterior para facilitar o calce<br><br>VERSÁTIL E MODERNA: Coringas para os dias mais frios ou chuvosos, as botas masculinas podem compor looks cheios de estilo que vão do urbano garage ao elegante, podendo ser usadas até mesmo para um visual mais formal para o trabalho!<br><br>RESISTENTE E ATEMPORAL: O Couro é o material obtido através da pele de animal curtida, e pode ter diversos acabamentos. Apresenta resistência e durabilidade, o que torna um material nobre muito utilizado na confecção de calçados, roupas e acessórios. A escolha perfeita para quem deseja um produto duradouro!<br><br>Sobre a marca: Há 30 anos a Colcci é considerada uma das marcas mais influentes da moda brasileira, graças aos seus produtos que aliam qualidade, sofisticação e informação de moda. A marca é um Must-Have de qualquer guarda-roupa, e conta com peças para todas as ocasiões.<br>Produto enviado com nota fiscal!', '18.00', '9.50', '28.00', '500.00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 1, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bota-chelsea-colcci-israel-cafe-3-1', 'webp', 10, 3), ('bota-chelsea-colcci-israel-cafe-3-2', 'webp', 10, 3), ('bota-chelsea-colcci-israel-cafe-3-3', 'webp', 10, 3), ('bota-chelsea-colcci-israel-cafe-3-4', 'webp', 10, 3), ('bota-chelsea-colcci-israel-cafe-3-5', 'webp', 10, 3);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (20, 200.90, 3, 10, 18), (23, 200.90, 3, 10, 19);

-- Feminino -> Roupas -> Camisas
INSERT INTO produto	(nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Camisa Calvin Klein Reta Listrada Rosa', 'Camisa Calvin Klein Reta Listrada Rosa Feminina', 'Camisa Calvin Klein Reta Listrada Rosa<br>Camisa GAP Reta Listrada Rosa Feminina<br>Camisa GAP Reta Listrada Rosa/Branca<br>Manga: Longa<br>Gola: Ponta<br>Fecho: Botão<br>Bolsos: 1<br>Medidas da peça no tamanho G: Ombro: 15cm/ Ombro a Ombro: 44cm/ Manga: 63cm/ Busto: 116cm /Comprimento: 64cm<br>Medidas do Modelo: Altura 1,81m / Busto: 102cm / Cintura: 84cm / Quadril: 113cm.<br>Produto enviado com nota fiscal!', '18.00', '5.00', '28.00', '200.00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 2, 2, 9, 6);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('camisa-calvin-klein-reta-listrada-rosa-4-1', 'webp', 11, 4), ('camisa-calvin-klein-reta-listrada-rosa-4-2', 'webp', 11, 4), ('camisa-calvin-klein-reta-listrada-rosa-4-3', 'webp', 11, 4), ('camisa-calvin-klein-reta-listrada-rosa-4-4', 'webp', 11, 4);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (19, 280.90, 4, 11, 2), (20, 280.90, 4, 11, 3), (20, 280.90, 4, 11, 4);

INSERT INTO produto	(nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Camisa Armadilho Manga Longa Algodão Branco', 'Camisa Armadilho Manga Longa Algodão Branco Feminina', 'Camisa Armadilho Manga Longa Algodão Branco<br>Camisa Armadilho Manga Longa Algodão Branco Feminina<br>Camisa manga longa básica algodão com poliamida e elastano, toque macio, ótimo caimento modelagem ajustada com pences. Fechamento botão.<br>Produto enviado com nota fiscal!', '18.00', '5.00', '28.00', '200.00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 2, 2, 9, 5);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('camisa-armadilho-manga-longa-algodao-branco-5-1', 'webp', 5, 5), ('camisa-armadilho-manga-longa-algodao-branco-5-2', 'webp', 5, 5), ('camisa-armadilho-manga-longa-algodao-branco-5-3', 'webp', 5, 5), ('camisa-armadilho-manga-longa-algodao-branco-5-4', 'webp', 5, 5);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (20, 300.90, 5, 5, 2), (20, 300.90, 5, 5, 3), (20, 300.90, 5, 5, 4);

INSERT INTO produto	(nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Camisa Facinelli by MOONCITY Amarração Rosa', 'Camisa Armadilho by MOONCITY Amarração Rosa Feminina', 'Camisa Armadilho by MOONCITY Amarração Rosa<br>Camisa Armadilho by MOONCITY Amarração Rosa Feminina<br>Modelagem: Reta<br>Gola: Ponta<br>Manga: Longa<br>Fecho: Botão<br>Detalhes: Possui amarração na barra. <br><br>Medidas da peça no tamanho P:<br>• Ombro: 14cm<br>• Ombro a ombro: 45cm<br>• Comprimento da manga: 65cm<br>• Largura da manga: 48cm<br>• Comprimento da peça: 66cm<br>• Busto: 118cm<br>Medidas do Modelo: Altura 1,70m/ Busto: 86cm/ Cintura: 65cm/ Quadril: 87cm.<br><br>CLÁSSICA E ELEGANTE: As camisas são peças obrigatórias em qualquer guarda-roupa, pois são super fáceis de combinar e dão automaticamente aquele ar arrumado ao look. Mas se engana quem acredita que ela não pode compor looks mais descontraídos. Basta usá-la de formas diferentes, como deixar um lado solto e outro dentro da calça ou até mesmo adicionar acessórios mais pesados para um visual diferente!<br>Produto enviado com nota fiscal!', '18.00', '5.00', '28.00', '200.00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 2, 2, 9, 5);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('camisa-facinelli-by-mooncity-amarracao-rosa-6-1', 'webp', 11, 6), ('camisa-facinelli-by-mooncity-amarracao-rosa-6-2', 'webp', 11, 6), ('camisa-facinelli-by-mooncity-amarracao-rosa-6-3', 'webp', 11, 6), ('camisa-facinelli-by-mooncity-amarracao-rosa-6-4', 'webp', 11, 6);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (20, 300.90, 6, 11, 2), (20, 300.90, 6, 11, 3);

-- Feminino -> Roupas -> Shorts
INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Short Feminino Fitness Amarração Marisa', 'Short Feminino Fitness Amarração Marisa Preto', 'Short Feminino Fitness Amarração Marisa<br>Short Feminino Fitness Amarração Marisa Preto<br>Short Feminino Fitness Amarração Marisa Short feminino moda fitness, confeccionado em tecido poliéster.<br> Possui cós com elástico e tira para amarração de ajuste, pequenos furos no tecido que auxiliam na ventilação, forro, acabamento e costura no tom.<br>Roupa Feminina - Moda Fitness - Bermudas e Shorts MODA FITNES.<br> Medidas da ModeloAltura: 1,79 Busto: 83cm Cintura: 64cmQuadril: 92cm Modelo veste tamanho: P', '18.00', '5.00', '28.00', '200.00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 2, 2, 12, 1);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('short-feminino-fitness-amarracao-marisa-7-1', 'webp', 10, 7), ('short-feminino-fitness-amarracao-marisa-7-2', 'webp', 10, 7), ('short-feminino-fitness-amarracao-marisa-7-3', 'webp', 10, 7), ('short-feminino-fitness-amarracao-marisa-7-4', 'webp', 10, 7);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (19, 80.90, 7, 10, 3), (19, 80.90, 7, 10, 4), (19, 80.90, 7, 10, 5);

-- Feminino -> Calçados -> Botas
INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bota Coturno Feminino Tratorada City DUBUY', 'Bota Coturno Feminino Tratorada City DUBUY Preto', 'Bota Coturno Feminino Tratorada City DUBUY<br>Bota Coturno Feminino Tratorada City DUBUY Preto<br>Bota Coturno Feminino Tratorada City DUBUY 1105LI Marrom/Capuccino ou Preto Fosco <br> <br>Marca: DUBUY <br>Numerações: 33 ao 42 <br>Zíper lateral <br>Forro antibacteriano <br>Altura do Salto: 4,2 cm <br>Altura do cano: 15,5 cm <br>Forma do calçado: Normal <br>Material Interno: Cacharrel espumado (confort) <br>Solado: Micro Expandido - (Antiderrapante – Tratorado) <br>Reforço de costura lateral do cabedal (dando mais durabilidade). <br>Diferencial: Bota estilo coturno com sola tratorada, que garante durabilidade, praticidade e conforto.<br>90 dias de Garantia contra defeito de Fabricação (Garantia apenas do calçado)<br>Produto enviado com nota fiscal!', '18.00', '5.00', '28.00', '200.00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 2, 1, 1, 2);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bota-coturno-feminino-tratorada-city-dubuy-8-1', 'webp', 10, 8), ('bota-coturno-feminino-tratorada-city-dubuy-8-2', 'webp', 10, 8), ('bota-coturno-feminino-tratorada-city-dubuy-8-3', 'webp', 10, 8);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (20, 89.90, 8, 10, 16), (20, 89.90, 8, 10, 17), (20, 99.90, 8, 10, 18);

-- Feminino -> Calçados -> Chinelos
INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Chinelo Colcci Rio Branco', 'Chinelo Colcci Rio Branco Techfit', 'Chinelo Colcci Rio Branco<br>Chinelo Colcci Rio Branco Techfit<br>Tecnologia: Techfit - um composto tecnológico desenvolvido exclusivamente para a Colcci. Além de usarmos material 100% vegano, nossa matéria prima é 100% reciclável e ecologicamente correto, podendo ser reutilizado para a fabricação de novos produtos.<br><br>Há 30 anos a Colcci é considerada uma das marcas mais influentes da moda brasileira, graças aos seus produtos que aliam qualidade, sofisticação e informação de moda. A marca é um Must-Have de qualquer guarda-roupa, e conta com peças para todas as ocasiões.<br><br>Peças essenciais para arrematar um look, os calçados versáteis com suas combinações fáceis e estilosas, são os modelos que ficam bem com qualquer tipo de visual e, por isso, são indispensáveis<br>Produto enviado com nota fiscal!', '18.00', '5.00', '28.00', '200.00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 2, 1, 2, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('chinelo-colcci-rio-branco-9-1', 'webp', 5, 9), ('chinelo-colcci-rio-branco-9-2', 'webp', 5, 9), ('chinelo-colcci-rio-branco-9-3', 'webp', 5, 9), ('chinelo-colcci-rio-branco-9-4', 'webp', 5, 9); 
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (33, 79.90, 9, 5, 16), (20, 79.90, 9, 5, 17), (20, 99.90, 9, 5, 18);

-- Feminino -> Calçados -> Crocs
INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Sandália Crocs Crocbrand', 'Sandália Crocs Crocbrand Azul Escuro', 'Chinelo Colcci Rio Branco<br>Sandália Crocs Crocbrand Azul Escuro<br>Bico: Redondo<br><br>Peças essenciais para arrematar um look, os calçados versáteis com suas combinações fáceis e estilosas, são os modelos que ficam bem com qualquer tipo de visual e, por isso, são indispensáveis.<br>Produto enviado com nota fiscal!', '18.00', '15.00', '28.00', '200.00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 2, 1, 4, 20);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('sandalia-crocs-crocbrand-10-1', 'webp', 3, 10), ('sandalia-crocs-crocbrand-10-2', 'webp', 3, 10), ('sandalia-crocs-crocbrand-10-3', 'webp', 3, 10), ('sandalia-crocs-crocbrand-10-4', 'webp', 3, 10), ('sandalia-crocs-crocbrand-10-5', 'webp', 3, 10);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (33, 79.90, 10, 3, 16), (43, 79.90, 10, 3, 17), (63, 79.90, 10, 3, 18), (10, 79.90, 10, 3, 19);

-- Feminino -> Calçados -> Tênis
INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Tênis adidas Originals Superstar', 'Tênis adidas Originals Superstar Branco', 'Tênis adidas Originals Superstar<br>Tênis adidas Originals Superstar Branco<br>Tênis adidas Originals Superstar Branco/Preto<br>Bico: Redondo<br>Fechamento: Cadarço<br>Ocasião/Estilo: Casual<br>Material Externo: Couro<br>Material Interno: Têxtil<br>Material da Sola: Sintético<br>Produto enviado com nota fiscal!', '18.00', '15.00', '28.00', '200.00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 2, 1, 6, 1);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('tenis-adidas-originals-superstar-11-1', 'webp', 5, 11), ('tenis-adidas-originals-superstar-11-2', 'webp', 5, 11), ('tenis-adidas-originals-superstar-11-3', 'webp', 5, 11), ('tenis-adidas-originals-superstar-11-4', 'webp', 5, 11), ('tenis-adidas-originals-superstar-11-5', 'webp', 5, 11), ('tenis-adidas-originals-superstar-11-6', 'webp', 5, 11);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (33, 79.90, 11, 5, 16), (33, 79.90, 11, 5, 17), (33, 80.90, 11, 5, 19);

-- Feminino -> Calçados -> Sapatênis
INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Tênis Game Advance', 'Tênis Game Advance em couro Branco', 'Tênis Game Advance<br>Tênis Game Advance em couro Branco<br>Cabedal em couro e tecido. Solado em borracha. Forro em tecido. Crocodilo verde bordado na lateralForro em material reciclado, para um modelo sustentável<br>Produto enviado com nota fiscal!', '18.00', '15.00', '28.00', '200.00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 2, 1, 5, 19);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('tenis-game-advance-12-1', 'webp', 5, 12), ('tenis-game-advance-12-2', 'webp', 5, 12), ('tenis-game-advance-12-3', 'webp', 5, 12), ('tenis-game-advance-12-4', 'webp', 5, 12), ('tenis-game-advance-12-5', 'webp', 5, 12);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (13, 79.90, 12, 5, 16), (23, 79.90, 12, 5, 17), (33, 80.90, 12, 5, 19);

-- Masculino -> Calçados -> Botas
INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bota Coturno Colcci Rodolfo Preta', 'Bota Coturno Colcci Rodolfo Preta', 'Bico: Redondo<br>Medidas da peça: 12x26cm (Altura X Circunferência)<br>Características: Possui solado tratorado<br><br>VERSÁTIL E MODERNA: Coringas para os dias mais frios ou chuvosos, as botas masculinas podem compor looks cheios de estilo que vão do urbano garage ao elegante, podendo ser usadas até mesmo para um visual mais formal para o trabalho!<br><br>RESISTENTE E ATEMPORAL: O Couro é o material obtido através da pele de animal curtida, e pode ter diversos acabamentos. Apresenta resistência e durabilidade, o que torna um material nobre muito utilizado na confecção de calçados, roupas e acessórios. A escolha perfeita para quem deseja um produto duradouro!<br><br>Sobre a marca: Há 30 anos a Colcci é considerada uma das marcas mais influentes da moda brasileira, graças aos seus produtos que aliam qualidade, sofisticação e informação de moda. A marca é um Must-Have de qualquer guarda-roupa, e conta com peças para todas as ocasiões.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 1, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bota-coturno-colcci-rodolfo-preta-13-1', 'webp', 10, 13), ('bota-coturno-colcci-rodolfo-preta-13-2', 'webp', 10, 13), ('bota-coturno-colcci-rodolfo-preta-13-3', 'webp', 10, 13), ('bota-coturno-colcci-rodolfo-preta-13-4', 'webp', 10, 13), ('bota-coturno-colcci-rodolfo-preta-13-5', 'webp', 10, 13), ('bota-coturno-colcci-rodolfo-preta-13-6', 'webp', 10, 13);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (13, 79.90, 13, 10, 16), (23, 79.90, 13, 10, 17), (33, 80.90, 13, 10, 19), (33, 80.90, 13, 10, 20);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bota Chelsea Colcci Dennys Preta', 'Bota Chelsea Colcci Dennys Preta', 'Bico: Redondo<br>Medidas da peça: 11x26cm (Altura X Circunferência)<br><br>VERSÁTIL E MODERNA: Coringas para os dias mais frios ou chuvosos, as botas masculinas podem compor looks cheios de estilo que vão do urbano garage ao elegante, podendo ser usadas até mesmo para um visual mais formal para o trabalho!<br><br>RESISTENTE E ATEMPORAL: O Couro é o material obtido através da pele de animal curtida, e pode ter diversos acabamentos. Apresenta resistência e durabilidade, o que torna um material nobre muito utilizado na confecção de calçados, roupas e acessórios. A escolha perfeita para quem deseja um produto duradouro!<br><br>Sobre a marca: Há 30 anos a Colcci é considerada uma das marcas mais influentes da moda brasileira, graças aos seus produtos que aliam qualidade, sofisticação e informação de moda. A marca é um Must-Have de qualquer guarda-roupa, e conta com peças para todas as ocasiões.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 1, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bota-chelsea-colcci-dennys-preta-14-1', 'webp', 10, 14), ('bota-chelsea-colcci-dennys-preta-14-2', 'webp', 10, 14), ('bota-chelsea-colcci-dennys-preta-14-3', 'webp', 10, 14), ('bota-chelsea-colcci-dennys-preta-14-4', 'webp', 10, 14), ('bota-chelsea-colcci-dennys-preta-14-5', 'webp', 10, 14), ('bota-chelsea-colcci-dennys-preta-14-6', 'webp', 10, 14);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (13, 79.90, 14, 10, 16), (23, 79.90, 14, 10, 17), (33, 80.90, 14, 10, 19), (33, 80.90, 14, 10, 20);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bota Chelsea Colcci Rafael Preta', 'Bota Chelsea Colcci Rafael Preta', 'Bota Chelsea Colcci Rafael Preta/Branca<br>Bico: Redondo<br>Medidas da peça: 13x28cm (Altura X Circunferência)<br>Características: Possui recorte em cor contrastante e solado tratorado<br><br>VERSÁTIL E MODERNA: Coringas para os dias mais frios ou chuvosos, as botas masculinas podem compor looks cheios de estilo que vão do urbano garage ao elegante, podendo ser usadas até mesmo para um visual mais formal para o trabalho!<br><br>RESISTENTE E ATEMPORAL: O Couro é o material obtido através da pele de animal curtida, e pode ter diversos acabamentos. Apresenta resistência e durabilidade, o que torna um material nobre muito utilizado na confecção de calçados, roupas e acessórios. A escolha perfeita para quem deseja um produto duradouro!<br><br>Sobre a marca: Há 30 anos a Colcci é considerada uma das marcas mais influentes da moda brasileira, graças aos seus produtos que aliam qualidade, sofisticação e informação de moda. A marca é um Must-Have de qualquer guarda-roupa, e conta com peças para todas as ocasiões.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 1, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bota-chelsea-colcci-rafael-preta-15-1', 'webp', 10, 15), ('bota-chelsea-colcci-rafael-preta-15-2', 'webp', 10, 15), ('bota-chelsea-colcci-rafael-preta-15-3', 'webp', 10, 15), ('bota-chelsea-colcci-rafael-preta-15-4', 'webp', 10, 15), ('bota-chelsea-colcci-rafael-preta-15-5', 'webp', 10, 15), ('bota-chelsea-colcci-rafael-preta-15-6', 'webp', 10, 15);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (13, 79.90, 15, 10, 16), (23, 79.90, 15, 10, 17), (33, 80.90, 15, 10, 19), (33, 80.90, 15, 10, 20);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bota Coturno Colcci Ronaldo Café', 'Bota Coturno Colcci Ronaldo Café', 'Bico: Redondo<br>Medidas da peça: 12x30cm (Altura X Circunferência)<br>Características: Possui solado tratorado<br><br>VERSÁTIL E MODERNA: Coringas para os dias mais frios ou chuvosos, as botas masculinas podem compor looks cheios de estilo que vão do urbano garage ao elegante, podendo ser usadas até mesmo para um visual mais formal para o trabalho!<br><br>RESISTENTE E ATEMPORAL: O Couro é o material obtido através da pele de animal curtida, e pode ter diversos acabamentos. Apresenta resistência e durabilidade, o que torna um material nobre muito utilizado na confecção de calçados, roupas e acessórios. A escolha perfeita para quem deseja um produto duradouro!<br><br>Sobre a marca: Há 30 anos a Colcci é considerada uma das marcas mais influentes da moda brasileira, graças aos seus produtos que aliam qualidade, sofisticação e informação de moda. A marca é um Must-Have de qualquer guarda-roupa, e conta com peças para todas as ocasiões.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 1, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bota-coturno-colcci-ronaldo-cafe-16-1', 'webp', 10, 16), ('bota-coturno-colcci-ronaldo-cafe-16-2', 'webp', 10, 16), ('bota-coturno-colcci-ronaldo-cafe-16-3', 'webp', 10, 16), ('bota-coturno-colcci-ronaldo-cafe-16-4', 'webp', 10, 16), ('bota-coturno-colcci-ronaldo-cafe-16-5', 'webp', 10, 16), ('bota-coturno-colcci-ronaldo-cafe-16-6', 'webp', 10, 16);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (13, 79.90, 16, 10, 16), (23, 79.90, 16, 10, 17), (33, 80.90, 16, 10, 19), (33, 80.90, 16, 10, 20), (33, 80.90, 16, 10, 21);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bota Colcci Pedro Café', 'Bota Colcci Pedro Café', 'Bico: Redondo<br>Medidas da peça: 11x24cm (Altura X Circunferência)<br><br>VERSÁTIL E MODERNA: Coringas para os dias mais frios ou chuvosos, as botas masculinas podem compor looks cheios de estilo que vão do urbano garage ao elegante, podendo ser usadas até mesmo para um visual mais formal para o trabalho!<br><br>RESISTENTE E ATEMPORAL: O Couro é o material obtido através da pele de animal curtida, e pode ter diversos acabamentos. Apresenta resistência e durabilidade, o que torna um material nobre muito utilizado na confecção de calçados, roupas e acessórios. A escolha perfeita para quem deseja um produto duradouro!<br><br>Sobre a marca: Há 30 anos a Colcci é considerada uma das marcas mais influentes da moda brasileira, graças aos seus produtos que aliam qualidade, sofisticação e informação de moda. A marca é um Must-Have de qualquer guarda-roupa, e conta com peças para todas as ocasiões.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 1, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bota-colcci-pedro-cafe-17-1', 'webp', 10, 17), ('bota-colcci-pedro-cafe-17-2', 'webp', 10, 17), ('bota-colcci-pedro-cafe-17-3', 'webp', 10, 17), ('bota-colcci-pedro-cafe-17-4', 'webp', 10, 17), ('bota-colcci-pedro-cafe-17-5', 'webp', 10, 17), ('bota-colcci-pedro-cafe-17-6', 'webp', 10, 17);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (13, 239.90, 17, 9, 16), (23, 239.90, 16, 9, 17), (33, 250.90, 17, 9, 19), (33, 250.90, 17, 9, 20), (33, 250.90, 17, 9, 21);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bota Coturno Colcci Tratorada Marrom', 'Bota Coturno Colcci Tratorada Marrom', 'Bico: Redondo<br>Medidas da peça no tamanho 38: 14x20cm (AxC)<br><br>Possui acabamento fosco texturizado.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 1, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bota-coturno-colcci-tratorada-marrom-18-1', 'webp', 10, 18), ('bota-coturno-colcci-tratorada-marrom-18-2', 'webp', 10, 18), ('bota-coturno-colcci-tratorada-marrom-18-3', 'webp', 10, 18), ('bota-coturno-colcci-tratorada-marrom-18-4', 'webp', 10, 18), ('bota-coturno-colcci-tratorada-marrom-18-5', 'webp', 10, 18);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (13, 269.90, 18, 9, 16), (23, 269.90, 18, 9, 18), (20, 250.90, 18, 9, 19), (40, 250.90, 18, 9, 20), (33, 250.90, 18, 9, 21);

-- Masculino -> Calçados -> Chinelos
INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Chinelo Colcci Logo', 'Chinelo Colcci Logo', '<br>ÍCONE BRASILEIRO: Os chinelos são uns dos calçados mais práticos, versáteis e confortáveis que se pode ter! Símbolo do alto-astral brasileiro, eles se tornaram itens indispensáveis no guarda-roupa, e podem ser usados desde a praia até um passeio no parque, basta escolher qual modelo e estampa mais te agrada, as opções são inúmeras.<br><br><br><br>Sobre a marca: Há 30 anos a Colcci é considerada uma das marcas mais influentes da moda brasileira, graças aos seus produtos que aliam qualidade, sofisticação e informação de moda. A marca é um Must-Have de qualquer guarda-roupa, e conta com peças para todas as ocasiões.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 2, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('chinelo-colcci-logo-19-1', 'webp', 5, 19), ('chinelo-colcci-logo-19-2', 'webp', 5, 19), ('chinelo-colcci-logo-19-3', 'webp', 5, 19), ('chinelo-colcci-logo-19-4', 'webp', 5, 19), ('chinelo-colcci-logo-19-5', 'webp', 5, 19);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('chinelo-colcci-logo-19-6', 'webp', 10, 19), ('chinelo-colcci-logo-19-7', 'webp', 10, 19), ('chinelo-colcci-logo-19-8', 'webp', 10, 19), ('chinelo-colcci-logo-19-9', 'webp', 10, 19), ('chinelo-colcci-logo-19-10', 'webp', 10, 19);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('chinelo-colcci-logo-19-11', 'webp', 3, 19), ('chinelo-colcci-logo-19-12', 'webp', 3, 19), ('chinelo-colcci-logo-19-13', 'webp', 3, 19), ('chinelo-colcci-logo-19-14', 'webp', 3, 19), ('chinelo-colcci-logo-19-15', 'webp', 3, 19);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (13, 45.50, 19, 5, 16), (23, 45.50, 16, 5, 17), (20, 45.50, 19, 5, 18), (40, 45.50, 19, 5, 20), (33, 45.50, 19, 5, 21), (13, 45.50, 19, 10, 16), (20, 45.50, 19, 10, 18), (40, 45.50, 19, 10, 20), (33, 45.50, 19, 10, 21), (40, 45.50, 19, 3, 20), (33, 45.50, 19, 3, 21);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Chinelo Slide adidas Originals Adilette Lite Preto', 'Chinelo Slide adidas Originals Adilette Lite Preto', 'Tipo de Produto: Chinelo<br>Tamanho: 38/39<br>Ocasião/Estilo: Casual<br>Material Externo: EVA<br>Material Interno: Têxtil<br>Material da Sola: EVA<br><br>ÍCONE BRASILEIRO: Os chinelos são uns dos calçados mais práticos, versáteis e confortáveis que se pode ter! Símbolo do alto-astral brasileiro, eles se tornaram itens indispensáveis no guarda-roupa, e podem ser usados desde a praia até um passeio no parque, basta escolher qual modelo e estampa mais te agrada, as opções são inúmeras.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 2, 1);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('chinelo-slide-adidas-originals-adilette-lite-preto-20-1', 'webp', 10, 20), ('chinelo-slide-adidas-originals-adilette-lite-preto-20-2', 'webp', 10, 20), ('chinelo-slide-adidas-originals-adilette-lite-preto-20-3', 'webp', 10, 20), ('chinelo-slide-adidas-originals-adilette-lite-preto-20-4', 'webp', 10, 20);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (13, 144.10, 20, 10, 16), (23, 144.10, 20, 10, 18), (20, 144.10, 20, 10, 19), (40, 144.10, 20, 10, 20), (33, 144.10, 20, 10, 21);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Chinelo Slide Colcci Logo Preto', 'Chinelo Slide Colcci Logo Preto', '<br>Possui logo em relevo na tira e acabamento translúcido<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 2, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('chinelo-slide-colcci-logo-preto-21-1', 'webp', 10, 21), ('chinelo-slide-colcci-logo-preto-21-2', 'webp', 10, 21), ('chinelo-slide-colcci-logo-preto-21-3', 'webp', 10, 21), ('chinelo-slide-colcci-logo-preto-21-4', 'webp', 10, 21), ('chinelo-slide-colcci-logo-preto-21-5', 'webp', 10, 21);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (13, 109.10, 21, 10, 16), (23, 109.10, 21, 10, 18), (21, 109.10, 21, 10, 19), (40, 109.10, 21, 10, 21);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Chinelo Reserva Color Block Azul', 'Chinelo Reserva Color Block Azul', 'Chinelo Reserva Color Block Azul/Vermelho<br><br>Possui logo da marca na tira e estampa decorativa<br><br>ÍCONE BRASILEIRO: Os chinelos são uns dos calçados mais práticos, versáteis e confortáveis que se pode ter! Símbolo do alto-astral brasileiro, eles se tornaram itens indispensáveis no guarda-roupa, e podem ser usados desde a praia até um passeio no parque, basta escolher qual modelo e estampa mais te agrada, as opções são inúmeras.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 2, 20);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('chinelo-reserva-color-block-azul-22-1', 'webp', 3, 22), ('chinelo-reserva-color-block-azul-22-2', 'webp', 3, 22), ('chinelo-reserva-color-block-azul-22-3', 'webp', 3, 22), ('chinelo-reserva-color-block-azul-22-4', 'webp', 3, 22), ('chinelo-reserva-color-block-azul-22-5', 'webp', 3, 22);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (13, 79.30, 22, 3, 16), (23, 79.30, 22, 3, 18), (22, 79.30, 22, 3, 19), (40, 79.30, 22, 3, 22);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Chinelo Havaianas Coqueiros Azul', 'Chinelo Havaianas Coqueiros Azul', '<br>ÍCONE BRASILEIRO: Os chinelos são uns dos calçados mais práticos, versáteis e confortáveis que se pode ter! Símbolo do alto-astral brasileiro, eles se tornaram itens indispensáveis no guarda-roupa, e podem ser usados desde a praia até um passeio no parque, basta escolher qual modelo e estampa mais te agrada, as opções são inúmeras.<br><br>ESTILOSO E CRUELTY-FREE: Os materiais sintéticos são produzidos a partir de compostos químicos, sendo uma ótima alternativa para quem deseja dispensar o uso de produtos de origem animal. Além disso, oferecem conforto e não deixam de lado o estilo!<br><br>Sobre a marca: Nascida em 1962, a Havaianas espalha o espírito brasileiro através de produtos icônicos, cheios de estilo, cores e conforto. Foi a marca pioneira no lançamento da sandália de dedo, inspirada do calçado japonês Zori, recebendo até patente pelo modelo.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 2, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('chinelo-havaianas-coqueiros-azul-23-1', 'webp', 3, 23), ('chinelo-havaianas-coqueiros-azul-23-2', 'webp', 3, 23), ('chinelo-havaianas-coqueiros-azul-23-3', 'webp', 3, 23), ('chinelo-havaianas-coqueiros-azul-23-4', 'webp', 3, 23), ('chinelo-havaianas-coqueiros-azul-23-5', 'webp', 3, 23);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (13, 79.30, 23, 3, 16), (23, 79.30, 23, 3, 18), (23, 79.30, 23, 3, 19), (40, 79.30, 23, 3, 22);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Chinelo Calvin Klein Lettering Preto', 'Chinelo Calvin Klein Lettering Preto', '<br>ÍCONE BRASILEIRO: Os chinelos são uns dos calçados mais práticos, versáteis e confortáveis que se pode ter! Símbolo do alto-astral brasileiro, eles se tornaram itens indispensáveis no guarda-roupa, e podem ser usados desde a praia até um passeio no parque, basta escolher qual modelo e estampa mais te agrada, as opções são inúmeras.<br><br>ESTILOSO E CRUELTY-FREE: Os materiais sintéticos são produzidos a partir de compostos químicos, sendo uma ótima alternativa para quem deseja dispensar o uso de produtos de origem animal. Além disso, oferecem conforto e não deixam de lado o estilo!<br><br>Sobre a marca: Completo sucesso, a Calvin Klein é ícone do minimalismo e da sofisticação na caminhada pelo concorrido universo da moda. Os produtos de linhas simples e sofisticadas colocaram a Calvin Klein entre as marcas de moda mais importantes e influentes do mercado, sendo sempre ousada, imponente e sem medo de abraçar culturas, discursos e pregar a despadronização.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 2, 6);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('chinelo-calvin-klein-lettering-preto-24-1', 'webp', 10, 24), ('chinelo-calvin-klein-lettering-preto-24-2', 'webp', 10, 24), ('chinelo-calvin-klein-lettering-preto-24-3', 'webp', 10, 24), ('chinelo-calvin-klein-lettering-preto-24-4', 'webp', 10, 24), ('chinelo-calvin-klein-lettering-preto-24-5', 'webp', 10, 24);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 79.10, 24, 10, 16), (24, 79.10, 24, 10, 18), (24, 79.10, 24, 10, 19), (40, 79.10, 24, 10, 22);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Chinelo Colcci Logo Preto', 'Chinelo Colcci Logo Preto', '<br>ÍCONE BRASILEIRO: Os chinelos são uns dos calçados mais práticos, versáteis e confortáveis que se pode ter! Símbolo do alto-astral brasileiro, eles se tornaram itens indispensáveis no guarda-roupa, e podem ser usados desde a praia até um passeio no parque, basta escolher qual modelo e estampa mais te agrada, as opções são inúmeras.<br><br>ESTILOSO E CRUELTY-FREE: Os materiais sintéticos são produzidos a partir de compostos químicos, sendo uma ótima alternativa para quem deseja dispensar o uso de produtos de origem animal. Além disso, oferecem conforto e não deixam de lado o estilo!<br><br>Sobre a marca: Há 30 anos a Colcci é considerada uma das marcas mais influentes da moda brasileira, graças aos seus produtos que aliam qualidade, sofisticação e informação de moda. A marca é um Must-Have de qualquer guarda-roupa, e conta com peças para todas as ocasiões.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 2, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('chinelo-colcci-logo-preto-25-1', 'webp', 10, 25), ('chinelo-colcci-logo-preto-25-2', 'webp', 10, 25), ('chinelo-colcci-logo-preto-25-3', 'webp', 10, 25), ('chinelo-colcci-logo-preto-25-4', 'webp', 10, 25), ('chinelo-colcci-logo-preto-25-5', 'webp', 10, 25);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 79.10, 25, 10, 16), (25, 79.10, 25, 10, 18), (25, 79.10, 25, 10, 19), (40, 79.10, 25, 10, 22);

-- Masculino -> Calçados -> Sapatênis
INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Sapatênis Lacoste Logo Azul Marinho', 'Sapatênis Lacoste Logo Azul Marinho', 'Bico: Redondo<br><br>Sobre a marca: Fundado pelo tenista tetracampeão internacional René Lacoste, a marca se inspira em valores esportivos, com alto padrão e ousadia, abordando um modelo de moda sustentável com produtos duráveis, levando em consideração o impacto ambiental<br><br>Peças essenciais para arrematar um look, os calçados versáteis com suas combinações fáceis e estilosas, são os modelos que ficam bem com qualquer tipo de visual e, por isso, são indispensáveis.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 5, 19);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('sapatenis-lacoste-logo-azul-marinho-26-1', 'webp', 3, 26), ('sapatenis-lacoste-logo-azul-marinho-26-2', 'webp', 3, 26), ('sapatenis-lacoste-logo-azul-marinho-26-3', 'webp', 3, 26), ('sapatenis-lacoste-logo-azul-marinho-26-4', 'webp', 3, 26), ('sapatenis-lacoste-logo-azul-marinho-26-5', 'webp', 3, 26);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 304.90, 26, 3, 16), (26, 304.90, 26, 3, 18), (26, 304.90, 26, 3, 19), (40, 304.90, 26, 3, 22);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Sapatênis Democrata Recortes Preto', 'Sapatênis Democrata Recortes Preto', 'Bico: Redondo<br><br>Possui acabamento texturizado e pespontos contrastantes<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 5, 21);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('sapatenis-democrata-recortes-preto-27-1', 'webp', 10, 27), ('sapatenis-democrata-recortes-preto-27-2', 'webp', 10, 27), ('sapatenis-democrata-recortes-preto-27-3', 'webp', 10, 27), ('sapatenis-democrata-recortes-preto-27-4', 'webp', 10, 27), ('sapatenis-democrata-recortes-preto-27-5', 'webp', 10, 27);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 179.90, 27, 10, 16), (28, 179.90, 27, 10, 18), (27, 179.90, 27, 10, 19), (40, 179.90, 27, 10, 22);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Sapatênis Democrata Recortes Off White', 'Sapatênis Democrata Recortes Off White', 'Bico: Redondo<br>Características: Possui recortes em camurça<br><br>ELEGANTE E VERSÁTIL: O sapatênis é a peça curinga no guarda-roupa dos homens. O modelo remete a elegância e sobriedade do sapato social, com um toque despojado do tênis, sendo uma aposta certeira para o ambiente de trabalho ou até mesmo para aquele visual sport chic.<br>_x000D_<br><br><br>Sobre a marca: Nascida em 1983, Democrata é referência no setor calçadista masculino, com modelos que aliam bem estar e elegância. A marca foi pioneira na produção de sapatos com solados Comfort, desenvolvendo a exclusiva tecnologia Air, que traz as famosas bolhas de ar que ajudam no caminhar com menos impacto. A Democrata também deu novos ares para botas e coturnos pesados com o conceito Garage, tornando os modelos referência, conquistando consumidores pelo Brasil e no mundo.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 5, 21);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('sapatenis-democrata-recortes-off-white-28-1', 'webp', 5, 28), ('sapatenis-democrata-recortes-off-white-28-2', 'webp', 5, 28), ('sapatenis-democrata-recortes-off-white-28-3', 'webp', 5, 28), ('sapatenis-democrata-recortes-off-white-28-4', 'webp', 5, 28), ('sapatenis-democrata-recortes-off-white-28-5', 'webp', 5, 28);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 169.90, 28, 5, 16), (27, 169.90, 28, 5, 18), (25, 169.90, 28, 5, 19), (40, 169.90, 28, 5, 22);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Tênis Sapatênis Masculino Casual Leve', 'Tênis Sapatênis Masculino Casual Leve', 'Os Sapatênis masculinos produzidos pela Polo oferecem um novo visual para quem busca conforto, qualidade e estilo. Trabalhados em material leve e resistente, nossos modelos chegaram para elevar seu look. O Sapatênis Polo oferece leveza ao caminhar graças ao seu solado macio e palmilha confort 4mm, perfeito para seu dia a dia.\n<br>\n<br>Especificações técnicas\n<br>\n<br>Material Interno: Lona Confortável\n<br>\n<br>Material Externo: Lona\n<br>\n<br>Solado: TR com costura lateral\n<br>\n<br>Palmilha: Palmilha confortável\n<br>\n<br>Destaques\n<br>\n<br>- Design Atual\n<br>\n<br>- Leveza, Conforto e qualidade\n<br>\n<br>- Material durável e moderno\n<br>\n<br>- Facilidade no calçado\n<br>\n<br>- Calça com facilidade\n<br>\n<br>- Produto fabricado pela marca\n<br>\n<br>Aprenda a cuidar do seu calçado\n<br>\n<br>- Jamais utilize produtos químicos para lavar seu calçado. Apenas água e sabão neutro, esfregue devagar em apenas um sentido.\n<br>\n<br>- O seu calçado também precisa de descanso. Os efeitos do uso rotineiro fazem com que sua durabilidade diminua.\n<br>\n<br>- Sempre retire seu calçado com as mãos, tirá-lo de outra forma fará com que seu material desgaste facilmente.\n<br>\n<br>- Evite guardar seu calçado em lugares com muita luz, procure um local arejado.\n<br>\n<br> \n<br>\n<br> \n<br>\n<br>NUMERAÇÃO DO TÊNIS: 37 AO 46\n<br>\n<br> \n<br>\n<br>37 ---------- 26 cm\n<br>\n<br>38 ---------- 26,5 cm\n<br>\n<br>39 ---------- 27,5 cm\n<br>\n<br>40 ---------- 28 cm\n<br>\n<br>41 ---------- 29,00 cm\n<br>\n<br>42 ---------- 29,30 cm\n<br>\n<br>43 ---------- 30,00 cm\n<br>\n<br>44 ---------- 30,30 cm\n<br>\n<br>45 ---------- 31,50 cm\n<br>\n<br>46 ---------- 31,80 cm<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 5, 21);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('tenis-sapatenis-masculino-casual-leve-29-1', 'webp', 10, 29), ('tenis-sapatenis-masculino-casual-leve-29-2', 'webp', 10, 29), ('tenis-sapatenis-masculino-casual-leve-29-3', 'webp', 10, 29), ('tenis-sapatenis-masculino-casual-leve-29-4', 'webp', 10, 29);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 169.90, 29, 10, 16), (27, 169.90, 29, 10, 18), (25, 169.90, 29, 10, 19), (40, 169.90, 29, 10, 22);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Sapatênis Democrata Recortes Marrom', 'Sapatênis Democrata Recortes Marrom', 'Bico: Redondo<br>Características: Possui perfuros frontais<br><br>ELEGANTE E VERSÁTIL: O sapatênis é a peça curinga no guarda-roupa dos homens. O modelo remete a elegância e sobriedade do sapato social, com um toque despojado do tênis, sendo uma aposta certeira para o ambiente de trabalho ou até mesmo para aquele visual sport chic.<br>_x000D_<br><br><br>Sobre a marca: Nascida em 1983, Democrata é referência no setor calçadista masculino, com modelos que aliam bem estar e elegância. A marca foi pioneira na produção de sapatos com solados Comfort, desenvolvendo a exclusiva tecnologia Air, que traz as famosas bolhas de ar que ajudam no caminhar com menos impacto. A Democrata também deu novos ares para botas e coturnos pesados com o conceito Garage, tornando os modelos referência, conquistando consumidores pelo Brasil e no mundo.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 5, 21);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('sapatenis-democrata-recortes-marrom-30-1', 'webp', 9, 30), ('sapatenis-democrata-recortes-marrom-30-2', 'webp', 9, 30), ('sapatenis-democrata-recortes-marrom-30-3', 'webp', 9, 30), ('sapatenis-democrata-recortes-marrom-30-4', 'webp', 9, 30), ('sapatenis-democrata-recortes-marrom-30-5', 'webp', 9, 30);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 169.90, 30, 9, 16), (27, 169.90, 30, 9, 18), (29, 169.90, 30, 9, 19), (40, 169.90, 30, 9, 22);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Sapatênis Ferracini Recortes Bege', 'Sapatênis Ferracini Recortes Bege', 'Bico: Redondo<br>Características: Possui logo lateral e recortes decorativos<br><br>ELEGANTE E VERSÁTIL: O sapatênis é a peça curinga no guarda-roupa dos homens. O modelo remete a elegância e sobriedade do sapato social, com um toque despojado do tênis, sendo uma aposta certeira para o ambiente de trabalho ou até mesmo para aquele visual sport chic.<br><br><br><br>RESISTENTE E ATEMPORAL: O Couro é o material obtido através da pele de animal curtida, e pode ter diversos acabamentos. Apresenta resistência e durabilidade, o que torna um material nobre muito utilizado na confecção de calçados, roupas e acessórios. A escolha perfeita para quem deseja um produto duradouro!<br><br>Sobre a marca: A Ferracini é uma das maiores empresas de calçados e acessórios masculinos do país. Seus produtos aliam qualidade e conforto, com modelos inspirados na necessidade do homem contemporâneo.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 1, 5, 22);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('sapatenis-ferracini-recortes-bege-31-1', 'webp', 5, 31), ('sapatenis-ferracini-recortes-bege-31-2', 'webp', 5, 31), ('sapatenis-ferracini-recortes-bege-31-3', 'webp', 5, 31), ('sapatenis-ferracini-recortes-bege-31-4', 'webp', 5, 31), ('sapatenis-ferracini-recortes-bege-31-5', 'webp', 5, 31), ('sapatenis-ferracini-recortes-bege-31-6', 'webp', 5, 31);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 165.50, 31, 5, 16), (27, 165.50, 31, 5, 18), (25, 165.50, 31, 5, 15), (40, 165.50, 31, 5, 22);

-- Masculino -> Roupas -> Bermudas
INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bermuda adidas Performance Reta Squadra 21 Preta', 'Bermuda adidas Performance Reta Squadra 21 Preta', 'Bermuda adidas Performance Reta Squadra 21 Preta/Branca<br>Fecho: Amarração<br>Altura da Cintura: Intermediária<br>Detalhes: Possui cós elástico com amarração interna e listras laterais bordadas.<br><br>Medidas da peça no tamanho M:<br>• Cintura: 72cm<br>• Quadril: 120cm<br>• Gancho: 30cm<br>• Comprimento: 47cm<br>Medidas do Modelo: Altura: 1,87m/ Tórax: 101cm/ Manequim: 42.<br><br>Tecnologia I: Aeroready - controla a umidade para manter o corpo seco e confortável. <br><br>Linha: Primegreen - fabricado com materiais reciclados, num esforço para acabar com desperdício de plástico. <br><br>TRENDY E ATEMPORAL: As bermudas são perfeitas para compor looks de verão casuais ou esportivos e ao mesmo tempo ficar confortável e estiloso! Aposte com blusas, t-shirts mais fluidas e leves, tênis ou sandálias para criar um visual moderno!<br><br>EFICIÊNCIA E COMPETITIVIDADE - Atletas no lugar mais alto do pódio. Quebras de recordes recorrentes. Limites superados. Milhões de vitórias e incontáveis títulos em diversas modalidades. Dificilmente em alguma dessas situações esportivas às clássicas “três listras” não estiveram presentes. Símbolo da mais alta eficiência e competitividade alemã nos esportes, a adidas Performance tem seu lugar nos corações que vibram nos treinos e competições por todo o mundo.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 2, 7, 1);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bermuda-adidas-performance-reta-squadra-21-preta-32-1', 'webp', 10, 32), ('bermuda-adidas-performance-reta-squadra-21-preta-32-2', 'webp', 10, 32), ('bermuda-adidas-performance-reta-squadra-21-preta-32-3', 'webp', 10, 32), ('bermuda-adidas-performance-reta-squadra-21-preta-32-4', 'webp', 10, 32), ('bermuda-adidas-performance-reta-squadra-21-preta-32-5', 'webp', 10, 32);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 160.10, 32, 10, 1), (27, 160.10, 32, 10, 2), (210, 160.10, 32, 10, 3), (40, 160.10, 32, 10, 4);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bermuda Jeans Colcci Reta Bolsos Azul', 'Bermuda Jeans Colcci Reta Bolsos Azul', 'Fecho: Botão e Zíper<br>Bolsos: 5<br>Altura da Cintura: Alta<br><br>Medidas da peça no tamanho 42:<br>• Cintura: 82cm<br>• Quadril: 112cm<br>• Gancho: 28cm<br>• Comprimento: 55cm<br>(Medidas com elasticidade)<br><br>Medidas do Modelo: Altura: 1,83m/ Tórax: 99cm/ Manequim: 38/40.<br><br>O TECIDO QUE AMAMOS: O jeans é um tecido queridinho no guarda-roupa atual! Por ser feito de algodão, é mais grosso, pesado e resistente, garantindo uma modelagem no corpo mais assertiva e que valoriza todos os biotipos. Ele é encontrado em diversos produtos, como calças, saias, bermudas, shorts e até mesmo jaquetas, é extremamente versátil e curinga. Ótimo para montar looks casuais ou formais, basta usar a criatividade pois as combinações são inúmeras!<br><br>Há 30 anos a Colcci é considerada uma das marcas mais influentes da moda brasileira.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 2, 7, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bermuda-jeans-colcci-reta-bolsos-azul-33-1', 'webp', 2, 33), ('bermuda-jeans-colcci-reta-bolsos-azul-33-2', 'webp', 2, 33), ('bermuda-jeans-colcci-reta-bolsos-azul-33-3', 'webp', 2, 33), ('bermuda-jeans-colcci-reta-bolsos-azul-33-4', 'webp', 2, 33), ('bermuda-jeans-colcci-reta-bolsos-azul-33-5', 'webp', 2, 33);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 160.80, 33, 2, 1), (27, 160.80, 33, 2, 2), (22, 160.80, 33, 2, 3), (40, 160.80, 33, 2, 4);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bermuda de Moletom adidas Originals Reta Essential Preta', 'Bermuda de Moletom adidas Originals Reta Essential Preta', 'Fecho: Amarração<br>Bolsos: 2<br>Altura da Cintura: Alta<br>Detalhes: Possui cós elástico com amarração interna, bolsos com fechos por zíperes, logo bordado e estrutura em moletom flanelado.<br><br>Medidas da peça no tamanho M:<br>• Cintura: 86cm<br>• Quadril: 122cm<br>• Gancho: 34cm<br>• Comprimento: 54cm<br>(Medidas com elasticidade)<br><br>Medidas do Modelo: Altura: 1,90m/ Tórax: 98cm/ Manequim: 42/44<br><br>Linha: End Plastic Waste - Produtos criados com materiais reciclados, para serem refeitos e desenvolvidos com a natureza. Nós vemos as possibilidades de fazer com que o melhor para o atleta seja melhor para o planeta, ajudando a acabar com o lixo plástico, para termos sempre onde praticar esportes.<br><br>TRENDY E ATEMPORAL: As bermudas são perfeitas para compor looks de verão casuais ou esportivos e ao mesmo tempo ficar confortável e estiloso! Aposte com blusas, t-shirts mais fluidas e leves, tênis ou sandálias para criar um visual moderno!<br><br>QUENTINHO E COMFY: O moletom é um tecido queridinho no guarda-roupa de muita gente, seu material é composto por fibras de algodão que dão um toque suave e macio a peça e também misturado com outras fibras garantindo modelagens e caimentos diversos! Ele pode ser flanelado, quando seu interior é macio com pelinhos, ou não flanelado que possui sua estrutura interna sem o acabamento peluciado. Ele é perfeito para um visual descolado e moderno!<br><br>Os produtos adidas Originals aliam tradição e modernidade em suas peças, sempre com o trefoil característico em destaque.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 2, 7, 1);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bermuda-de-moletom-adidas-originals-reta-essential-preta-34-1', 'webp', 10, 34), ('bermuda-de-moletom-adidas-originals-reta-essential-preta-34-2', 'webp', 10, 34), ('bermuda-de-moletom-adidas-originals-reta-essential-preta-34-3', 'webp', 10, 34), ('bermuda-de-moletom-adidas-originals-reta-essential-preta-34-4', 'webp', 10, 34), ('bermuda-de-moletom-adidas-originals-reta-essential-preta-34-5', 'webp', 10, 34);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 160.80, 34, 10, 1), (107, 160.80, 34, 10, 2), (1010, 160.80, 34, 10, 3), (40, 160.80, 34, 10, 4), (40, 160.80, 34, 10, 5);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bermuda Jeans Colcci Reta Bolsos Azul', 'Bermuda Jeans Colcci Reta Bolsos Azul', 'Fecho: Botão e Zíper<br>Bolsos: 5<br>Altura da Cintura: Alta<br><br>Medidas da peça no tamanho 42:<br>• Cintura: 82cm<br>• Quadril: 112cm<br>• Gancho: 28cm<br>• Comprimento: 55cm<br>(Medidas com elasticidade)<br><br>Medidas do Modelo: Altura: 1,83m/ Tórax: 99cm/ Manequim: 38/40.<br><br>O TECIDO QUE AMAMOS: O jeans é um tecido queridinho no guarda-roupa atual! Por ser feito de algodão, é mais grosso, pesado e resistente, garantindo uma modelagem no corpo mais assertiva e que valoriza todos os biotipos. Ele é encontrado em diversos produtos, como calças, saias, bermudas, shorts e até mesmo jaquetas, é extremamente versátil e curinga. Ótimo para montar looks casuais ou formais, basta usar a criatividade pois as combinações são inúmeras!<br><br>Há 30 anos a Colcci é considerada uma das marcas mais influentes da moda brasileira.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 2, 7, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bermuda-jeans-colcci-reta-bolsos-azul-35-1', 'webp', 2, 35), ('bermuda-jeans-colcci-reta-bolsos-azul-35-2', 'webp', 2, 35), ('bermuda-jeans-colcci-reta-bolsos-azul-35-3', 'webp', 2, 35), ('bermuda-jeans-colcci-reta-bolsos-azul-35-4', 'webp', 2, 35), ('bermuda-jeans-colcci-reta-bolsos-azul-35-5', 'webp', 2, 35);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 160.80, 35, 2, 1), (27, 160.80, 35, 2, 2), (22, 160.80, 35, 2, 3), (40, 160.80, 35, 2, 4), (40, 160.80, 35, 2, 5);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Bermuda Hering Básica Chino Em Sarja Preto', 'Bermuda Hering Básica Chino Em Sarja Preto', '\n                        Na modelagem Chino, esta peça tem estilo de alfaiataria, mas é feita de algodão e possui recorte mais despojado. É a soma perfeita de sofisticação e conforto. Você, 100% bem, é básico!<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 2, 7, 23);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('bermuda-hering-basica-chino-em-sarja-preto-36-1', 'webp', 10, 36), ('bermuda-hering-basica-chino-em-sarja-preto-36-2', 'webp', 10, 36), ('bermuda-hering-basica-chino-em-sarja-preto-36-3', 'webp', 10, 36), ('bermuda-hering-basica-chino-em-sarja-preto-36-4', 'webp', 10, 36), ('bermuda-hering-basica-chino-em-sarja-preto-36-5', 'webp', 10, 36);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 160.80, 36, 10, 1), (107, 160.80, 36, 10, 2), (1010, 160.80, 36, 10, 3), (40, 160.80, 36, 10, 4), (40, 160.80, 36, 10, 5);

-- Masculino -> Roupas -> Calças
INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Calça Sarja Calvin Klein Jeans Skinny Lisa Preta', 'Calça Sarja Calvin Klein Jeans Skinny Lisa Preta', 'Fecho: Botão e Zíper<br>Bolsos: 5<br>Altura da Cintura: Intermediária<br><br>Medidas da peça no tamanho 40:<br>• Cintura: 86cm<br>• Quadril: 112cm<br>• Gancho: 26cm<br>• Comprimento: 108cm<br>Medidas do Modelo: Altura: 1,84m/ Tórax: 92cm/ Manequim: 38.<br><br><br>CONFORTO E SOFISTICAÇÃO: As calças de tecidos são ótimas para compor aquele look de trabalho, com cortes retos e mais estruturados. Porém, são super versáteis e podem se transformar em looks despojados para curtir o happy hour em segundos! Basta adicionar uma camiseta estampada, brincar com texturas e acessórios e trocar o salto por um tênis ou bota.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 2, 8, 6);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('calca-sarja-calvin-klein-jeans-skinny-lisa-preta-37-1', 'webp', 10, 37), ('calca-sarja-calvin-klein-jeans-skinny-lisa-preta-37-2', 'webp', 10, 37), ('calca-sarja-calvin-klein-jeans-skinny-lisa-preta-37-3', 'webp', 10, 37), ('calca-sarja-calvin-klein-jeans-skinny-lisa-preta-37-4', 'webp', 10, 37), ('calca-sarja-calvin-klein-jeans-skinny-lisa-preta-37-5', 'webp', 10, 37);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 160.80, 37, 10, 1), (107, 160.80, 37, 10, 2), (1010, 160.80, 37, 10, 3), (40, 160.80, 37, 10, 4), (40, 160.80, 37, 10, 5);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Calça Jeans Skinny Pentagono Masculina Azul Estonado', 'Calça Jeans Skinny Pentagono Masculina Azul Estonado', 'Se fossemos explicar o que a Calça Jeans Masculina em uma única palavra, essa palavra seria: estilo. Com seu corte skinny e lavagem moderna, é perfeita para qualquer tipo de evento ou até mesmo no dia a dia. Quer conhecer mais da Calça Jeans Masculina? Então vamos lá:<br><br> <br><br>- Dois bolsos dianteiros pensados para guardar celulares;<br><br>- Dois bolsos traseiros, confortáveis e seguros;<br><br>- Elastano para melhor adaptação e modelagem no corpo;<br><br>- Modelagem pensada de forma moderna e adaptável.<br><br> <br><br>Disponível em diversos tamanhos, a Calça Jeans Masculina é feita para qualquer pessoa que queira aliar o conforto com o estilo em seu dia a dia. Se você não abre mão de estar sempre bem arrumado e confortável, esse modelo de calça é perfeito para você.<br><br> <br><br>Precisando de mais modelos para compor seu look? Adicione a Calça Jeans Masculina ao carrinho e dê uma olhada em nosso catálogo de roupas, você encontrará tudo o que precisa para estar sempre na moda e preparado.<br><br> <br><br>Na KS CASUAL &amp; SPORT você encontra a roupa certa para cada momento. Aqui é o lugar que você procurava para repaginar seu guarda-roupa com estilo e ótimos valores. Não perca mais tempo e mostre ao mundo seu novo eu, com roupas estilosas e cheias de personalidade.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 2, 8, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('calca-jeans-skinny-pentagono-masculina-azul-estonado-38-1', 'webp', 3, 38), ('calca-jeans-skinny-pentagono-masculina-azul-estonado-38-2', 'webp', 3, 38), ('calca-jeans-skinny-pentagono-masculina-azul-estonado-38-3', 'webp', 3, 38), ('calca-jeans-skinny-pentagono-masculina-azul-estonado-38-4', 'webp', 3, 38);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 160.80, 38, 3, 1), (37, 160.80, 38, 3, 2), (33, 160.80, 38, 3, 3), (40, 160.80, 38, 3, 4), (40, 160.80, 38, 3, 5);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Calça Hering Chino Alfaiataria Azul Marinho', 'Calça Hering Chino Alfaiataria Azul Marinho', 'Fecho: Botão e Zíper<br>Bolsos: 3<br>Altura da Cintura: Alta<br><br>Medidas da peça no tamanho 42:<br>• Cintura: 82cm<br>• Quadril: 102cm<br>• Gancho: 30cm<br>• Comprimento: 105cm<br>(Medidas sem elasticidade)<br><br>Medidas do Modelo: Altura: 1,89m/ Tórax: 102cm/ Manequim: 42/44.<br><br>SOFISTICADA E LEVE: A modelagem CHINO remete à alfaiataria, é solta e confortável, de corte reto ou amplo, confeccionada em algodão e possui bolsos faca que dão um toque elegante a produção. Por sua modelagem não marcar o corpo, ela é uma ótima alternativa para dias mais quentes de verão, se tornando uma peça-chave no guarda-roupa!<br><br>CONFORTO E SOFISTICAÇÃO: As calças de tecidos são ótimas para compor aquele look casual ou de trabalho, com cortes retos e mais estruturados. Porém, são super versáteis e podem se transformar em looks despojados para curtir o happy hour em segundos! Basta adicionar uma camiseta estampada, brincar com texturas e acessórios e trocar o salto por um tênis ou bota.<br><br>Com coleções que primam pelo conforto e pelo estilo, a Hering tem se reinventado constantemente ao longo de mais de 130 anos, trazendo peças em sintonia com as tendências da moda atual, mantendo sua identidade e tradição. Sendo a primeira marca brasileira de vestuário, sua história apresenta também uma longa trajetória de responsabilidade social e ambiental, com linhas sustentáveis que priorizam a reutilização de tecidos.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 2, 8, 23);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('calca-hering-chino-alfaiataria-azul-marinho-39-1', 'webp', 3, 39), ('calca-hering-chino-alfaiataria-azul-marinho-39-2', 'webp', 3, 39), ('calca-hering-chino-alfaiataria-azul-marinho-39-3', 'webp', 3, 39), ('calca-hering-chino-alfaiataria-azul-marinho-39-4', 'webp', 3, 39), ('calca-hering-chino-alfaiataria-azul-marinho-39-5', 'webp', 3, 39);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 160.80, 39, 3, 1), (37, 160.80, 39, 3, 2), (33, 160.80, 39, 3, 3), (40, 160.80, 39, 3, 4), (40, 160.80, 39, 3, 5);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Calça Jeans Skinny Onix Masculina Preto', 'Calça Jeans Skinny Onix Masculina Preto', 'Se fossemos explicar o que a Calça Jeans Masculina em uma única palavra, essa palavra seria: estilo. Com seu corte skinny e lavagem moderna, é perfeita para qualquer tipo de evento ou até mesmo no dia a dia. Quer conhecer mais da Calça Jeans Masculina? Então vamos lá:  - Dois bolsos dianteiros pensados para guardar celulares; - Dois bolsos traseiros, confortáveis e seguros; - Elastano para melhor adaptação e modelagem no corpo; - Modelagem pensada de forma moderna e adaptável.  Disponível em diversos tamanhos, a Calça Jeans Masculina é feita para qualquer pessoa que queira aliar o conforto com o estilo em seu dia a dia. Se você não abre mão de estar sempre bem arrumado e confortável, esse modelo de calça é perfeito para você.  Precisando de mais modelos para compor seu look? Adicione a Calça Jeans Masculina ao carrinho e dê uma olhada em nosso catálogo de roupas, você encontrará tudo o que precisa para estar sempre na moda e preparado.  Na Fiuza Fashion você encontra a roupa certa para cada momento. Aqui é o lugar que você procurava para repaginar seu guarda-roupa com estilo e ótimos valores. Não perca mais tempo e mostre ao mundo seu novo eu, com roupas estilosas e cheias de personalidade.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 2, 8, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('calca-jeans-skinny-onix-masculina-preto-40-1', 'webp', 10, 40), ('calca-jeans-skinny-onix-masculina-preto-40-2', 'webp', 10, 40), ('calca-jeans-skinny-onix-masculina-preto-40-3', 'webp', 10, 40);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 160.80, 40, 10, 1), (107, 160.80, 40, 10, 2), (1010, 160.80, 40, 10, 3), (40, 160.80, 40, 10, 4), (40, 160.80, 40, 10, 5);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Calça adidas Performance Slim Sereno Azul Marinho', 'Calça adidas Performance Slim Sereno Azul Marinho', 'Fecho: Amarração<br>Bolsos: 2<br>Altura da Cintura: Alta<br>Estampa: Logo<br>Detalhes: Possui cós elástico.<br>Estilo: Performance<br><br>Medidas da peça no tamanho M:<br>• Cintura: 76cm<br>• Quadril: 100cm<br>• Gancho: 35cm<br>• Comprimento: 102cm<br>(Medidas sem elasticidade)<br><br>Medidas do Modelo: Altura: 1,85m/ Tórax: 97cm/ Manequim: 40.<br><br>CONFORTÁVEL E DEMOCRÁTICA: a modelagem SLIM é atemporal e vai bem com tudo, desde looks mais casuais a formais. Aposte com peças mais soltas e sobreposições para criar um equilíbrio na produção.<br><br>CONFORTO E SOFISTICAÇÃO: As calças de tecidos são ótimas para compor aquele look casual ou de trabalho, com cortes retos e mais estruturados. Porém, são super versáteis e podem se transformar em looks despojados para curtir o happy hour em segundos! Basta adicionar uma camiseta estampada, brincar com texturas e acessórios e trocar o salto por um tênis ou bota.<br><br>SUSTENTÁVEL E CONSCIENTE: O poliéster reciclado foi desenvolvido usando as garrafas de água de plástico transparente, ou PET como matéria-prima. Extremamente sustentável, promove uma circulação de peças mais consciente, garantindo assim uma alternativa para quem busca looks estilosos sem agredir o meio ambiente!<br><br>EFICIÊNCIA E COMPETITIVIDADE - Atletas no lugar mais alto do pódio. Quebras de recordes recorrentes. Limites superados. Milhões de vitórias e incontáveis títulos em diversas modalidades. Dificilmente em alguma dessas situações esportivas às clássicas “três listras” não estiveram presentes. Símbolo da mais alta eficiência e competitividade alemã nos esportes, a adidas Performance tem seu lugar nos corações que vibram nos treinos e competições por todo o mundo.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 2, 8, 1);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('calca-adidas-performance-slim-sereno-azul-marinho-41-1', 'webp', 3, 41), ('calca-adidas-performance-slim-sereno-azul-marinho-41-2', 'webp', 3, 41), ('calca-adidas-performance-slim-sereno-azul-marinho-41-3', 'webp', 3, 41), ('calca-adidas-performance-slim-sereno-azul-marinho-41-4', 'webp', 3, 41), ('calca-adidas-performance-slim-sereno-azul-marinho-41-5', 'webp', 3, 41);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 187.80, 41, 3, 1), (107, 187.80, 41, 3, 2), (1010, 187.80, 41, 3, 3), (40, 187.80, 41, 3, 4), (40, 187.80, 41, 3, 5);

-- Masculino -> Roupas -> Camisas
INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Camisa Mr Kitsch Reta Estampada Verde', 'Camisa Mr Kitsch Reta Estampada Verde', 'Modelagem: Reta<br>Gola: Ponta<br>Manga: Longa<br>Fecho: Botão<br>Estampa: Full Print<br>Detalhes: Possui logo bordado.<br><br>Medidas da peça no tamanho M:<br>• Ombro: 19cm<br>• Ombro a ombro: 48cm<br>• Comprimento da manga: 68cm<br>• Largura da manga: 34cm<br>• Comprimento da peça: 68cm<br>• Tórax: 116cm<br><br>(Medidas sem elasticidade)<br><br>Medidas do Modelo: Altura: 1,89m/ Tórax: 100cm/ Manequim: 40.<br><br>CLÁSSICA E ELEGANTE: As camisas são peças obrigatórias em qualquer guarda-roupa, pois são super fáceis de combinar e dão automaticamente aquele ar arrumado ao look. Mas se engana quem acredita que ela não pode compor looks mais descontraídos. Basta usá-la de formas diferentes, como deixar um lado solto e outro dentro da calça ou até mesmo adicionar acessórios mais pesados para um visual diferente!<br><br>Fundada em 1986, a Mr. Kitsch possui foco no público masculino com linhas de roupas estilosas e impecáveis, sempre com a preocupação de fabricar com as melhores matérias primas encontradas no mercado. A marca é fruto de pesquisa de comportamento, estilo, mobilidade urbana e referências internacionais.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 2, 9, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('camisa-mr-kitsch-reta-estampada-verde-42-1', 'webp', 13, 42), ('camisa-mr-kitsch-reta-estampada-verde-42-2', 'webp', 13, 42), ('camisa-mr-kitsch-reta-estampada-verde-42-3', 'webp', 13, 42), ('camisa-mr-kitsch-reta-estampada-verde-42-4', 'webp', 13, 42), ('camisa-mr-kitsch-reta-estampada-verde-42-5', 'webp', 13, 42);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 160.80, 42, 13, 1), (137, 160.80, 42, 13, 2), (1313, 160.80, 42, 13, 3), (40, 160.80, 42, 13, 4), (40, 160.80, 42, 13, 5);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Camisa Colcci Reta Lisa Branca', 'Camisa Colcci Reta Lisa Branca', 'Modelagem: Reta<br>Gola: Ponta<br>Manga: Longa<br>Fecho: Botão<br>Detalhes: Possui logo bordado.<br><br>Medidas da peça no tamanho M:<br>• Ombro: 16cm<br>• Ombro a ombro: 49cm<br>• Comprimento da manga: 69cm<br>• Largura da manga: 40cm<br>• Comprimento da peça: 73cm<br>• Tórax: 114cm<br><br>(Medidas sem elasticidade)<br><br>Medidas do Modelo: Altura: 1,89m/ Tórax: 100cm/ Manequim: 40.<br><br>CLÁSSICA E ELEGANTE: As camisas são peças obrigatórias em qualquer guarda-roupa, pois são super fáceis de combinar e dão automaticamente aquele ar arrumado ao look. Mas se engana quem acredita que ela não pode compor looks mais descontraídos. Basta usá-la de formas diferentes, como deixar um lado solto e outro dentro da calça ou até mesmo adicionar acessórios mais pesados para um visual diferente!<br><br>Há 30 anos a Colcci é considerada uma das marcas mais influentes da moda brasileira.<br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 2, 9, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('camisa-colcci-reta-lisa-branca-43-1', 'webp', 5, 43), ('camisa-colcci-reta-lisa-branca-43-2', 'webp', 5, 43), ('camisa-colcci-reta-lisa-branca-43-3', 'webp', 5, 43), ('camisa-colcci-reta-lisa-branca-43-4', 'webp', 5, 43);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 160.80, 43, 5, 1), (57, 160.80, 43, 5, 2), (55, 160.80, 43, 5, 3), (40, 160.80, 43, 5, 4), (40, 160.80, 43, 5, 5);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Camisa Aramis Reta Oxford Preta', 'Camisa Aramis Reta Oxford Preta', 'Modelagem: Reta<br>Gola: Ponta<br>Manga: Longa<br>Fecho: Botão<br>Bolsos: 1<br>Detalhes: Possui bolso frontal com logo bordado.<br><br>Medidas da peça no tamanho M:<br>• Ombro: 17cm<br>• Ombro a ombro: 49cm<br>• Comprimento da manga: 67cm<br>• Largura da manga: 50cm<br>• Comprimento da peça: 65cm<br>• Tórax: 116cm<br><br>(Medidas sem elasticidade)<br><br>Medidas do Modelo: Altura: 1,80m/ Tórax: 99cm/ Manequim: 42.<br><br>CLÁSSICA E ELEGANTE: As camisas são peças obrigatórias em qualquer guarda-roupa, pois são super fáceis de combinar e dão automaticamente aquele ar arrumado ao look. Mas se engana quem acredita que ela não pode compor looks mais descontraídos. Basta usá-la de formas diferentes, como deixar um lado solto e outro dentro da calça ou até mesmo adicionar acessórios mais pesados para um visual diferente!<br><br>FRESQUINHO E CONFORTÁVEL: Composto por algodão, o tricoline é um tecido leve, fresco e confortável. É bastante utilizado na confecção de peças elegantes como camisas, calças e roupas sociais, mas também é encontrado em peças mais casuais e divertidas com estampas e modelagens modernas. Por ser um tecido respirável, ele logo se tornou preferência em climas tropicais e nos dias quentes de verão!<br><br>Criada em 1995 e pioneira no trabalho com fio egípcio no mercado brasileiro. A proposta da grife Aramis é baseada em moda masculina moderna e sofisticada, com poder de inovação, prezando por elegância e conforto.                    <br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 2, 9, 7);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('camisa-aramis-reta-oxford-preta-44-1', 'webp', 10, 44), ('camisa-aramis-reta-oxford-preta-44-2', 'webp', 10, 44), ('camisa-aramis-reta-oxford-preta-44-3', 'webp', 10, 44), ('camisa-aramis-reta-oxford-preta-44-4', 'webp', 10, 44);
INSERT INTO estoque (quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (11, 160.80, 44, 10, 1), (107, 160.80, 44, 10, 2), (1010, 160.80, 44, 10, 3), (40, 160.80, 44, 10, 4), (40, 160.80, 44, 10, 5);

INSERT INTO produto (nome, descricao, detalhe, largura, altura, comprimento, peso, data_cadastro, data_atualizacao, ativo, genero_id, categoria_id, tipo_id, marca_id) VALUES ('Camisa adidas Performance Estro 19 Vermelha', 'Camisa adidas Performance Estro 19 Vermelha', '\n                        Manga: Curta<br>Gola: Redonda<br>Medidas da peça no tamanho M: Ombro: 14cm/ Ombro a Ombro: 48cm/ Manga: 23cm/ Tórax: 114cm /Comprimento: 75cm<br>Medidas do Modelo: Altura 1,91m/ Tórax 91cm/ Manequim 38.<br>Tecnologia: Climalite: O tecido elimina suor para manter sua pele seca em qualquer condição climática                    <br>Produto enviado com nota fiscal!', 27.00, 14.00, 34.00, 500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 1, 2, 9, 1);
INSERT INTO imagem (nome, tipo, cor_id, produto_id) VALUES ('camisa-adidas-performance-estro-19-vermelha-45-1', 'webp', 16, 45), ('camisa-adidas-performance-estro-19-vermelha-45-2', 'webp', 16, 45), ('camisa-adidas-performance-estro-19-vermelha-45-3', 'webp', 16, 45), ('camisa-adidas-performance-estro-19-vermelha-45-4', 'webp', 16, 45), ('camisa-adidas-performance-estro-19-vermelha-45-5', 'webp', 16, 45);
INSERT INTO estoque (oferta, quantidade, preco, produto_id, cor_id, tamanho_id) VALUES (20, 11, 160.80, 45, 16, 1), (20, 167, 160.80, 45, 16, 2), (20, 16, 160.80, 45, 16, 3), (20, 40, 160.80, 45, 16, 4), (20, 40, 160.80, 45, 16, 5);






